language: java
sudo: false
install: true
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "tykvik-travis-ci"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - sonar
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar