language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "tykvik-github"
    token:
      secure: $SONAR_TOKEN
    branches:
      - sonar
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar